### ISSUE TITLE
zeit "now" deployment isn't working

### ISSUE THREAD

**Issue by diverent2** [diverent2/flagfinder#11]
# 🐞 bug report

now deployment fails because it can't run the app

## Current behavior 👎

Deployment fails 😢 

```sh
> Finished in 3.2s. Type node __sapper__/build to run the app.
--
08:17:32 PM | Done in 3.35s.
08:17:32 PM | Error: No output directory named "export" found.
08:17:32 PM | More details: https://zeit.co/docs/v2/advanced/platform/frequently-asked-questions#missing-public-directory
08:17:32 PM | at validateDistDir (/zeit/55cfbb27218c985e/.build-utils/.builder/node_modules/@now/static-build/dist/index.js:308:15)
08:17:32 PM | at Object.build (/zeit/55cfbb27218c985e/.build-utils/.builder/node_modules/@now/static-build/dist/index.js:503:13)
08:17:32 PM | at <anonymous>
08:17:32 PM | at process._tickDomainCallback (internal/process/next_tick.js:228:7)
08:17:32 PM | worker exited with code 20 and signal null
08:17:34 PM | done
```

see: [deployment error (for owner only)](https://zeit.co/diverent2/flagfinder/85p0jiawh)

## Expected behavior 👍

now executes these commands

1. yarn build
2. yarn start

## Further information

This could help [switch to `now v1`](https://spectrum.chat/zeit/now/cannot-create-now-v1-deployments~d206a0d4-5835-4af5-bb5c-a17f0171fb25)

### Explanation

`now v2` is completely serverless see [zeit blog](https://zeit.co/blog/now-2)

**Comment by diverent2** [comment]
Solved via https://www.npmjs.com/package/now-sapper

For reference: https://github.com/thgh/sapper-template/commit/220307c800525633063df3e3373bc76d0e62cd86
